@extends('pdf/base')


@section('title')
    {{ trans('pdf.debt_social_work_report_from_to', ['initial_date' => date('d/m/Y', strtotime($initial_date)), 'ended_date' => date('d/m/Y', strtotime($ended_date))]) }}
@endsection

@section('style')
    <style>
        #first_column {
            position: absolute;
            top: 1%;
            width: 100px;
        }

        #second_column {
            margin-left: 17%;
        }

        .cover {
            background: #FFFFA6;
        }

        .cover td {
            width: 150mm;
        }

        .small {
            width: 20mm;
        }

        .medium {
            width: 30mm;
        }

        .large {
            width: 80mm;
        }
    </style>
@endsection

@section('header')
    <div id="first_column">
        <img width="80" height="80" src="{{ asset('images/logo.png') }}">
    </div>

    <div id="second_column">
        <table class="cover">
            <tr>
                <td class="title"> {{ trans('pdf.debt_social_work_report_from_to', ['initial_date' => date('d/m/Y', strtotime($initial_date)), 'ended_date' => date('d/m/Y', strtotime($ended_date))]) }}
                </td>
            </tr>
        </table>

        <br/>

        <table class="cover">
            <tr>
                <td> Date: {{ date('d/m/Y') }}  </td>
            </tr>

            <tr>
                <td> Generated by: {{ auth()->user()->name }}</td>
            </tr>
        </table>
    </div>
@endsection

@section('body')
    <table style="margin-top: 3%" border="1" cellspacing="0">
        <tr>
            <td class="small"><strong> {{ trans('pdf.month') }} </strong></td>
            <td class="small"><strong> {{ trans('pdf.year') }}</strong></td>
            <td class="large"><strong> {{ trans('social_works.social_work') }}</strong></td>
            <td class="medium"><strong> {{ trans('pdf.total_amount') }} </strong></td>
        </tr>

        @foreach ($social_works as $social_work)
            <tr>
                <td> {{ $social_work->month }} </td>
                <td> {{ $social_work->year }} </td>
                <td> {{ $social_work->social_work }} </td>
                <td> ${{ $social_work->total_amount }} </td>
            </tr>
        @endforeach
    </table>
@endsection
