@extends('pdf/base')


@section('title')
    {{ trans('pdf.patients_flow_report_from_to', ['initial_date' => date('d/m/Y', strtotime($initial_date)), 'ended_date' => date('d/m/Y', strtotime($ended_date))]) }}
@endsection

@section('style')
    <style>
        #first_column {
            position: absolute;
            top: 1%;
            width: 100px;
        }

        #second_column {
            margin-left: 17%;
        }

        .cover {
            background: #FFFFA6;
        }

        .cover td {
            width: 150mm;
        }
    </style>
@endsection

@section('header')
    <div id="first_column">
        <img width="80" height="80" src="{{ asset('images/logo.png') }}">
    </div>

    <div id="second_column">
        <table class="cover">
            <tr>
                <td class="title"> {{ trans('pdf.patients_flow_report_from_to', ['initial_date' => date('d/m/Y', strtotime($initial_date)), 'ended_date' => date('d/m/Y', strtotime($ended_date))]) }}
                </td>
            </tr>
        </table>

        <br/>

        <table class="cover">
            <tr>
                <td> Date: {{ date('d/m/Y') }}  </td>
            </tr>

            <tr>
                <td> Generated by: {{ auth()->user()->name }}</td>
            </tr>
        </table>
    </div>
@endsection

@section('body')
    <table style="margin-top: 3%" border="1" cellspacing="0">
        <caption> {{ trans('pdf.total_records') }}: {{ $protocols->count() }} </caption>
        <tr>
            <td style="width: 100px"><strong> {{ trans('pdf.date') }} </strong></td>
            <td style="width: 200px"><strong> {{ trans('patients.patient') }}</strong></td>
            <td style="width: 100px"><strong> {{ trans('patients.identification_number') }}</strong></td>
            <td style="width: 100px"><strong> {{ trans('patients.phone') }} </strong></td>
            <td style="width: 200px"><strong> {{ trans('patients.email') }} </strong></td>
        </tr>

        @foreach ($protocols as $protocol)
            <tr>
                <td> {{ date('d/m/Y', strtotime($protocol->completion_date))  }} </td>
                <td> {{ $protocol->patient->full_name  }} </td>
                <td> {{ $protocol->patient->key  }} </td>
                <td> {{ $protocol->patient->phone }} </td>
                <td> {{ $protocol->patient->email }} </td>

            </tr>
        @endforeach
    </table>
@endsection
