@extends('pdf/base')

@section('title')
{{ trans('pdf.social_work_debt_report_from_to', ['social_work' => $social_work->name, 'start_date' => \Carbon\Carbon::parse($start_date)->format(Drops::getSystemParameterValueByKey('DATE_FORMAT')), 'end_date' => \Carbon\Carbon::parse($end_date)->format(Drops::getSystemParameterValueByKey('DATE_FORMAT'))]) }}
@endsection

@section('style')
    <style>
        #first_column {
            position: absolute;
            top: 1%;
            width: 100px;
        }

        #second_column {
            margin-left: 17%;
        }

        .cover {
            background: #FFFFA6;
        }

        .cover td {
            width: 150mm;
        }

        .billingPeriodsTable td {
            text-align: center;
        }
    </style>
@endsection

@section('header')
    <div id="first_column">
        <img style="margin-top: 20px" src="{{ asset('images/small_logo.png') }}">
    </div>

    <div id="second_column">
        <table class="cover">
            <tr>
                <td class="title"> 
                    {{ trans('pdf.social_work_debt_report_from_to', ['social_work' => $social_work->name, 'start_date' => \Carbon\Carbon::parse($start_date)->format(Drops::getSystemParameterValueByKey('DATE_FORMAT')), 'end_date' => \Carbon\Carbon::parse($end_date)->format(Drops::getSystemParameterValueByKey('DATE_FORMAT'))]) }}
                </td>
            </tr>
        </table>

        <br/>

        <table class="cover">
            <tr>
                <td> Date: {{ date(Drops::getSystemParameterValueByKey('DATE_FORMAT')) }}  </td>
            </tr>

            <tr>
                <td> Generated by: {{ auth()->user()->name }}</td>
            </tr>
        </table>
    </div>
@endsection

@section('content')
    <table class="billingPeriodsTable" style="margin-top: 3%; width: 100%" border="1" cellspacing="0">
        <tr>
            <td> <strong> {{ trans('billing_periods.billing_period') }} </strong></td>
            <td> <strong> {{ trans('billing_periods.start_date') }} </strong> </td>
            <td> <strong> {{ trans('billing_periods.end_date') }} </strong> </td>
            <td> <strong> {{ trans('pdf.total_paid') }} </strong> </td>
        </tr>

        @foreach ($billing_periods as $billing_period)
            <tr>
                <td> {{ $billing_period->name }} </td>
                <td> {{ \Carbon\Carbon::parse($billing_period->start_date)->format(Drops::getSystemParameterValueByKey('DATE_FORMAT')) }} </td>
                <td> {{ \Carbon\Carbon::parse($billing_period->end_date)->format(Drops::getSystemParameterValueByKey('DATE_FORMAT')) }} </td>
                <td>
                    ${{ number_format($billing_period->total_collection, Drops::getSystemParameterValueByKey('DECIMALS'), Drops::getSystemParameterValueByKey('DECIMAL_SEPARATOR'), Drops::getSystemParameterValueByKey('THOUSANDS_SEPARATOR')) }}

                    @if ($billing_period->total_collection > 0)
                        ({{ number_format($billing_period->total_paid * 100 / $billing_period->total_collection, Drops::getSystemParameterValueByKey('DECIMALS'), Drops::getSystemParameterValueByKey('DECIMAL_SEPARATOR'), Drops::getSystemParameterValueByKey('THOUSANDS_SEPARATOR')) }}%)
                    @else
                        (0%)
                    @endif
                </td>
            </tr>
        @endforeach
    </table>
@endsection
