@extends('pdf/base')


@section('title')
    {{ trans('pdf.patients_flow_report_from_to', ['start_date' => $start_date, 'end_date' => $end_date]) }}
@endsection

@section('style')
    <style>
        #first_column {
            position: absolute;
            top: 1%;
            width: 100px;
        }

        #second_column {
            margin-left: 17%;
        }

        .cover {
            background: #FFFFA6;
        }

        .cover td {
            width: 150mm;
        }

        .text-center {
            text-align: center;
        }

        .patientsTable td {
            text-align: center;
        }
    </style>
@endsection

@section('header')
    <div id="first_column">
        <img style="margin-top: 20px" src="{{ asset('images/small_logo.png') }}">
    </div>

    <div id="second_column">
        <table class="cover">
            <tr>
                <td class="title"> {{ trans('pdf.patients_flow_report_from_to', ['start_date' => $start_date, 'end_date' => $end_date]) }}
                </td>
            </tr>
        </table>

        <br/>

        <table class="cover">
            <tr>
                <td> Date: {{ date('Y-m-d') }}  </td>
            </tr>

            <tr>
                <td> Generated by: {{ auth()->user()->name }}</td>
            </tr>
        </table>
    </div>
@endsection

@section('body')
    <table style="margin-top: 3%; width: 100%" class="patientsTable" border="1" cellspacing="0">
        <caption> {{ trans('pdf.total_records') }}: {{ $protocols->count() }} </caption>
        <tr>
            <td style="width: 100px"><strong> {{ trans('pdf.date') }} </strong></td>
            <td style="width: 200px"><strong> {{ trans('patients.patient') }}</strong></td>
            <td style="width: 100px"><strong> {{ trans('patients.identification_number') }}</strong></td>
            <td style="width: 100px"><strong> {{ trans('patients.contact') }} </strong></td>
        </tr>

        @foreach ($protocols as $protocol)
            <tr>
                <td> {{ $protocol->completion_date }} </td>
                <td> {{ $protocol->internalPatient->full_name }} </td>
                <td> {{ $protocol->internalPatient->identification_number }} </td>
                <td> 
                    {{ $protocol->internalPatient->phone }} <br />
                    {{ $protocol->internalPatient->email }} 
                </td>
            </tr>
        @endforeach
    </table>
@endsection
