@extends('pdf/base')

@section('title')
{{ trans('pdf.protocols_report_from_to', ['start_date' => \Carbon\Carbon::parse($start_date)->format(Drops::getSystemParameterValueByKey('DATE_FORMAT')), 'end_date' => \Carbon\Carbon::parse($end_date)->format(Drops::getSystemParameterValueByKey('DATE_FORMAT'))]) }}
@endsection

@section('style')
    <style>
        #first_column {
            position: absolute;
            top: 1%;
            width: 100px;
        }

        #second_column {
            margin-left: 17%;
        }

        .cover {
            background: #FFFFA6;
        }

        .cover td {
            width: 150mm;
        }

        .protocolsTable td {
            text-align: center;
        }
    </style>
@endsection

@section('header')
    <div id="first_column">
        <img style="margin-top: 20px" src="{{ asset('images/small_logo.png') }}">
    </div>

    <div id="second_column">
        <table class="cover">
            <tr>
                <td class="title"> {{ trans('pdf.protocols_report_from_to', ['start_date' => \Carbon\Carbon::parse($start_date)->format(Drops::getSystemParameterValueByKey('DATE_FORMAT')), 'end_date' => \Carbon\Carbon::parse($end_date)->format(Drops::getSystemParameterValueByKey('DATE_FORMAT'))]) }}
                </td>
            </tr>
        </table>

        <br/>

        <table class="cover">
            <tr>
                <td> Date: {{ date(Drops::getSystemParameterValueByKey('DATE_FORMAT')) }}  </td>
            </tr>

            <tr>
                <td> Generated by: {{ auth()->user()->name }}</td>
            </tr>
        </table>
    </div>
@endsection


@section('content')
    <table style="margin-top: 3%; width: 100%" class="protocolsTable" border="1" cellspacing="0">
        <caption style="margin-top: 1%"> {{ trans('pdf.total_records') }}: {{ $protocols->count() }} </caption>
        <tr>
            <td> <strong> {{ trans('pdf.date') }} </strong></td>
            <td> <strong> {{ trans('protocols.protocol_number') }} </strong></td>
            <td> <strong> {{ trans('patients.patient') }}</strong></td>
            <td> <strong> {{ trans('social_works.social_work') }}</strong></td>
            <td> <strong> {{ trans('protocols.total_amount') }} </strong></td>
        </tr>

        @php $total_collection = 0; @endphp

        @foreach ($protocols as $protocol)
            <tr>
                <td> {{ \Carbon\Carbon::parse($protocol->completion_date)->format(Drops::getSystemParameterValueByKey('DATE_FORMAT')) }} </td>
                <td> {{ $protocol->id  }} @if (! empty($protocol->closed)) * @endif </td>
                <td> {{ $protocol->internalPatient->full_name }} </td>
                <td> {{ $protocol->plan->social_work->acronym}} </td>
                <td>
                    @php $total_collection += $protocol->total_price; @endphp

                    ${{ number_format($protocol->total_price, Drops::getSystemParameterValueByKey('DECIMALS'), Drops::getSystemParameterValueByKey('DECIMAL_SEPARATOR'), Drops::getSystemParameterValueByKey('THOUSANDS_SEPARATOR')) }}
                </td>
            </tr>
        @endforeach

        <tr>
            <td colspan="4"> </td>
            <td> ${{ number_format($total_collection, Drops::getSystemParameterValueByKey('DECIMALS'), Drops::getSystemParameterValueByKey('DECIMAL_SEPARATOR'), Drops::getSystemParameterValueByKey('THOUSANDS_SEPARATOR')) }} </td>
        </tr>
    </table>
   
    <p>
        * Protocol closed
    </p>
@endsection



