@extends('pdf/base')

@section('title')
{{ trans('pdf.protocols_report_from_to', ['start_date' => $start_date, 'end_date' => $end_date]) }}
@endsection

@section('style')
    <style>
        #first_column {
            position: absolute;
            top: 1%;
            width: 100px;
        }

        #second_column {
            margin-left: 17%;
        }

        .cover {
            background: #FFFFA6;
        }

        .cover td {
            width: 150mm;
        }

        .small {
            width: 20mm;
        }

        .medium {
            width: 30mm;
        }

        .large {
            width: 80mm;
        }

        .text-center {
            text-align: center;
        }
    </style>
@endsection

@section('header')
    <div id="first_column">
        <img style="margin-top: 20px" src="{{ asset('images/small_logo.png') }}">
    </div>

    <div id="second_column">
        <table class="cover">
            <tr>
                <td class="title"> {{ trans('pdf.protocols_report_from_to', ['start_date' => $start_date, 'end_date' => $end_date]) }}
                </td>
            </tr>
        </table>

        <br/>

        <table class="cover">
            <tr>
                <td> Date: {{ date('Y-m-d') }}  </td>
            </tr>

            <tr>
                <td> Generated by: {{ auth()->user()->name }}</td>
            </tr>
        </table>
    </div>
@endsection


@section('body')
    <table style="margin-top: 3%" border="1" cellspacing="0">
        <caption> {{ trans('pdf.total_records') }}: {{ $protocols->count() }} </caption>
        <tr>
            <td class="small text-center"> <strong> {{ trans('pdf.date') }} </strong></td>
            <td class="small text-center"> <strong> {{ trans('protocols.protocol_number') }} </strong></td>
            <td class="large"><strong> {{ trans('patients.patient') }}</strong></td>
            <td class="medium text-center"><strong> {{ trans('social_works.social_work') }}</strong></td>
            <td class="medium text-center"><strong> {{ trans('protocols.total_amount') }} </strong></td>
        </tr>

        @php $total_collection = 0; @endphp

        @foreach ($protocols as $protocol)
            <tr>
                <td class="text-center"> {{ $protocol->completion_date }} </td>
                <td class="text-center"> {{ $protocol->id  }} </td>
                <td> {{ $protocol->internalPatient->full_name }} </td>
                <td class="text-center"> {{ $protocol->plan->social_work->acronym}} </td>
                <td class="text-center">
                    @php $total_collection += $protocol->total_price; @endphp

                    ${{ $protocol->total_price }}
                </td>
            </tr>
        @endforeach

        <tr>
            <td> </td>
            <td> </td>
            <td> </td>
            <td>  </td>
            <td class="text-center"> ${{ $total_collection }} </td>
        </tr>
    </table>
@endsection



